# Generated by Django 6.0.3 on 2026-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_fix_waiting_for_tg_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(choices=[('gpt_image_2', 'GPT Image 2 (Tavsiya etilgan)'), ('hybrid', 'Hybrid (OpenCV Fallback)'), ('opencv', 'OpenCV Only')], default='gpt_image_2', max_length=50),
        ),
    ]
